host = "{{Host}}"
schema = "{{Schema}}"
secret = "{{Secret}}"

[info]
name = "{{Name}}"
icon = "{{Image}}"
pubkey = "{{Pubkey}}"
description = "{{Description}}"

[management]
enabled = true

[roles.member]
can_invite = true

[roles.admin]
can_manage = true
pubkeys = {{{AdminPubkeys}}}
